pipeline:
  eslint:
    image: node:latest
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
    when: [pull_request]
    commands: 
      - npm install --silent
      - npm run lint
branches: [ master, "*:master" ]
